ALTER TABLE appointments 
ADD COLUMN deposit_amount DECIMAL(10,2) DEFAULT 0,
ADD COLUMN is_deposit_paid BOOLEAN DEFAULT FALSE,
ADD COLUMN reminder_24h_sent BOOLEAN DEFAULT FALSE,
ADD COLUMN reminder_2h_sent BOOLEAN DEFAULT FALSE,
ADD COLUMN rebooking_nudge_sent BOOLEAN DEFAULT FALSE;
